/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package sistema.de.facturacion;

import java.awt.AWTException;
import java.awt.Dimension;
import java.awt.Graphics;
import java.awt.Rectangle;
import java.awt.Robot;
import java.awt.Toolkit;
import java.awt.event.WindowAdapter;
import java.awt.event.WindowEvent;
import java.awt.event.WindowListener;
import java.awt.image.BufferedImage;
import java.io.File;
import java.io.IOException;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.imageio.ImageIO;
import javax.swing.DefaultListModel;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.SpinnerNumberModel;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Julio
 */
public class ReporteVenta extends javax.swing.JFrame {

    /**
     * Creates new form proovedor
     */
    private ResultSet rsVenta;
    private DefaultTableModel modeloTabla;
    private DefaultListModel modeloListaVenta;

    public ReporteVenta() {
        initComponents();
        tablaFactura.getTableHeader().setReorderingAllowed(false);
        modeloTabla = (DefaultTableModel) tablaFactura.getModel();
        this.setLocationRelativeTo(null);
        WindowListener exitListener = new WindowAdapter() {

            @Override
            public void windowClosing(WindowEvent e) {
                new menu().setVisible(true);
            }
        };
        this.addWindowListener(exitListener);

        String sql = "SELECT venta.fecha_venta,venta.id_venta, venta.total_venta,  "
                + "cliente.cedula_rif, cliente.nombre_cliente,  cliente.apellido_cliente,cliente.domicilio_cliente FROM public.venta "
                + "INNER JOIN public.cliente ON venta.id_cliente=cliente.serial "
                + " GROUP BY venta.id_venta,cliente.cedula_rif,cliente.nombre_cliente,cliente.apellido_cliente,cliente.domicilio_cliente "
                + " ORDER BY venta.id_venta";

        try {
            Statement st = Conexion.getConnection().createStatement(ResultSet.TYPE_SCROLL_SENSITIVE, ResultSet.CONCUR_READ_ONLY);
            rsVenta = st.executeQuery(sql);
            modeloListaVenta = new DefaultListModel();
            while (rsVenta.next()) {
                modeloListaVenta.addElement("N° " + rsVenta.getObject("id_venta") + " TOTAL: "
                        + rsVenta.getObject("total_venta") + " Cliente: " + rsVenta.getObject("nombre_cliente") + " "
                        + rsVenta.getObject("apellido_cliente"));
            }
            listaFacturas.setModel(modeloListaVenta);
        } catch (Exception ex) {
            Logger.getLogger(Login.class.getName()).log(Level.SEVERE, null, ex);
        }

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        dialogo = new javax.swing.JDialog();
        jScrollPane3 = new javax.swing.JScrollPane();
        texto = new javax.swing.JTextArea();
        jLabel3 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        tfTotal = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        tfSubTotal = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        tfIva = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jBSalir = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        tablaFactura = new javax.swing.JTable();
        lbfecha = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        lbNombre = new javax.swing.JLabel();
        label3 = new javax.swing.JLabel();
        lbCedulaRif = new javax.swing.JLabel();
        lbNumeroVenta = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        listaFacturas = new javax.swing.JList();
        tfBusqueda = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        lbDireccion = new javax.swing.JLabel();
        btImprimir = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        dialogo.addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosed(java.awt.event.WindowEvent evt) {
                dialogoWindowClosed(evt);
            }
        });

        texto.setColumns(20);
        texto.setRows(5);
        jScrollPane3.setViewportView(texto);

        javax.swing.GroupLayout dialogoLayout = new javax.swing.GroupLayout(dialogo.getContentPane());
        dialogo.getContentPane().setLayout(dialogoLayout);
        dialogoLayout.setHorizontalGroup(
            dialogoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 400, Short.MAX_VALUE)
            .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        dialogoLayout.setVerticalGroup(
            dialogoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, dialogoLayout.createSequentialGroup()
                .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, 115, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 174, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel8.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("SUBTOTAL");
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 480, -1, -1));

        tfTotal.setEditable(false);
        tfTotal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfTotalActionPerformed(evt);
            }
        });
        getContentPane().add(tfTotal, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 480, 110, -1));

        jLabel10.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setText("TOTAL VENTA");
        getContentPane().add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 480, -1, -1));

        tfSubTotal.setEditable(false);
        getContentPane().add(tfSubTotal, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 480, 90, -1));

        jLabel9.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("IVA");
        getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 470, 40, 30));

        tfIva.setEditable(false);
        tfIva.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfIvaActionPerformed(evt);
            }
        });
        getContentPane().add(tfIva, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 480, 120, -1));

        jLabel2.setFont(new java.awt.Font("Tahoma", 2, 18)); // NOI18N
        jLabel2.setText("Nombre y Apellido");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 50, 150, -1));

        jLabel4.setFont(new java.awt.Font("Tahoma", 2, 18)); // NOI18N
        jLabel4.setText("Fecha");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 20, 50, -1));

        jBSalir.setText("Atras");
        jBSalir.setMinimumSize(new java.awt.Dimension(134, 29));
        jBSalir.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jBSalirMouseClicked(evt);
            }
        });
        jBSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBSalirActionPerformed(evt);
            }
        });
        getContentPane().add(jBSalir, new org.netbeans.lib.awtextra.AbsoluteConstraints(780, 20, 130, 40));

        tablaFactura.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Codigo", "Producto", "Descripcion", "Cantidad", "Precio", "Importe"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.String.class, java.lang.Integer.class, java.lang.Float.class, java.lang.Float.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tablaFactura.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        jScrollPane2.setViewportView(tablaFactura);

        getContentPane().add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 130, 640, 340));

        lbfecha.setFont(new java.awt.Font("Tahoma", 2, 18)); // NOI18N
        getContentPane().add(lbfecha, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 20, 150, 20));

        jLabel16.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/SIGCA(LOGO)_1 pequeño.png"))); // NOI18N
        getContentPane().add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 410, 220, 80));

        jLabel11.setFont(new java.awt.Font("Tahoma", 2, 18)); // NOI18N
        jLabel11.setText("NUMERO DE VENTA");
        getContentPane().add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, 170, -1));

        lbNombre.setFont(new java.awt.Font("Tahoma", 2, 18)); // NOI18N
        lbNombre.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        getContentPane().add(lbNombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 50, 360, 20));

        label3.setFont(new java.awt.Font("Tahoma", 2, 18)); // NOI18N
        label3.setText("DIRECCIÓN");
        getContentPane().add(label3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 105, 130, -1));

        lbCedulaRif.setFont(new java.awt.Font("Tahoma", 2, 18)); // NOI18N
        lbCedulaRif.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        getContentPane().add(lbCedulaRif, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 85, 150, 20));

        lbNumeroVenta.setFont(new java.awt.Font("Tahoma", 2, 18)); // NOI18N
        lbNumeroVenta.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        getContentPane().add(lbNumeroVenta, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 20, 150, 20));

        listaFacturas.setFont(new java.awt.Font("Tahoma", 0, 9)); // NOI18N
        listaFacturas.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                listaFacturasMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(listaFacturas);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 170, 250, 230));

        tfBusqueda.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        tfBusqueda.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                tfBusquedaKeyReleased(evt);
            }
        });
        getContentPane().add(tfBusqueda, new org.netbeans.lib.awtextra.AbsoluteConstraints(780, 130, 130, 30));

        jLabel5.setText(" o nombre de Cliente");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 150, 100, 20));

        jLabel6.setText("Busqueda por N°");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 130, 90, 20));

        jLabel7.setFont(new java.awt.Font("Tahoma", 2, 18)); // NOI18N
        jLabel7.setText("CEDULA O RIF");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 80, 130, -1));

        lbDireccion.setFont(new java.awt.Font("Tahoma", 2, 18)); // NOI18N
        lbDireccion.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        getContentPane().add(lbDireccion, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 105, 430, 20));

        btImprimir.setText("Imprimir");
        btImprimir.setMinimumSize(new java.awt.Dimension(134, 29));
        btImprimir.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btImprimirMouseClicked(evt);
            }
        });
        btImprimir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btImprimirActionPerformed(evt);
            }
        });
        getContentPane().add(btImprimir, new org.netbeans.lib.awtextra.AbsoluteConstraints(780, 70, 130, 40));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/WINDOWS_7_WALLPAPER_BY_AMYSTIKALDESIGNS.JPG"))); // NOI18N
        jLabel1.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                jLabel1MouseMoved(evt);
            }
        });
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 930, 510));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jLabel1MouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel1MouseMoved

        // TODO add your handling code here:
    }//GEN-LAST:event_jLabel1MouseMoved


    private void tfIvaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfIvaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfIvaActionPerformed

    private void jBSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBSalirActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jBSalirActionPerformed

    private void jBSalirMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jBSalirMouseClicked
        dispose();
        new Venta().setVisible(true);
    }//GEN-LAST:event_jBSalirMouseClicked

    private void tfTotalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfTotalActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfTotalActionPerformed

    private void listaFacturasMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_listaFacturasMouseClicked
        try {

            if (rsVenta == null || listaFacturas.getSelectedIndex() == -1) {
                return;
            }

            rsVenta.absolute(listaFacturas.getSelectedIndex() + 1);

            lbNumeroVenta.setText(rsVenta.getString("id_venta"));
            lbNombre.setText(rsVenta.getString("nombre_cliente") + " " + rsVenta.getString("apellido_cliente"));
            lbCedulaRif.setText(rsVenta.getString("cedula_rif"));
            lbfecha.setText(rsVenta.getDate("fecha_venta").toString());
            lbDireccion.setText(rsVenta.getString("domicilio_cliente"));

            String sql = "SELECT venta.id_venta,  detalle_venta.cantidad,detalle_venta.importe, "
                    + "producto.nombre_producto,producto.descripcion_producto,  producto.id_producto, producto.precio_producto "
                    + "FROM public.venta "
                    + "INNER JOIN public.detalle_venta ON venta.id_venta=detalle_venta.id_venta "
                    + "INNER JOIN public.producto ON detalle_venta.id_producto=producto.id_producto "
                    + "WHERE venta.id_venta =" + rsVenta.getInt("id_venta")
                    + "ORDER BY id_venta ";

            Statement st = Conexion.getConnection().createStatement(ResultSet.TYPE_SCROLL_SENSITIVE, ResultSet.CONCUR_READ_ONLY);
            ResultSet rs = st.executeQuery(sql);

            int cant = modeloTabla.getRowCount();
            for (int i = 0; i < cant; i++) {
                modeloTabla.removeRow(0);
            }

            float subTotal = 0f;

            while (rs.next()) {
                subTotal += rs.getFloat("precio_producto") * rs.getInt("cantidad");
                modeloTabla.addRow(new Object[]{
                    rs.getInt("id_producto"),
                    rs.getString("nombre_producto"),
                    rs.getString("descripcion_producto"),
                    rs.getInt("cantidad"),
                    rs.getFloat("precio_producto"),
                    subTotal
                });
            }

            tfSubTotal.setText(subTotal + "");
            tfIva.setText((subTotal * 0.12) + "");
            tfTotal.setText(rsVenta.getFloat("total_venta") + "");
        } catch (SQLException ex) {
            Logger.getLogger(cliente.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_listaFacturasMouseClicked

    private void tfBusquedaKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tfBusquedaKeyReleased
        try {
            rsVenta.beforeFirst();
            int pos = 0;
            while (rsVenta.next()) {
                if (rsVenta.getString("nombre_cliente").toLowerCase().contains(tfBusqueda.getText().toLowerCase())
                        || rsVenta.getString("id_venta").contains(tfBusqueda.getText())) {
                    listaFacturas.setSelectedIndex(pos);
                    break;
                }
                pos++;
            }
        } catch (SQLException ex) {
            Logger.getLogger(Venta.class.getName()).log(Level.SEVERE, null, ex);
        }

    }//GEN-LAST:event_tfBusquedaKeyReleased

    private void btImprimirMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btImprimirMouseClicked
        Dimension size = this.getSize();
        BufferedImage img = new BufferedImage(size.width, size.height, BufferedImage.TYPE_3BYTE_BGR);
        Graphics g = img.getGraphics();
        this.paint(g);
        g.dispose();
        
        try {
            ImageIO.write(img, "png", new File(
                    new JFileChooser().getFileSystemView().getDefaultDirectory().toString()+"/factura"+lbNumeroVenta.getText()+".png"));
        } catch (IOException ex) {
            ex.printStackTrace();
        }
    }//GEN-LAST:event_btImprimirMouseClicked

    private void btImprimirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btImprimirActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btImprimirActionPerformed

    private void dialogoWindowClosed(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_dialogoWindowClosed
        texto.setText("");
    }//GEN-LAST:event_dialogoWindowClosed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;

                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ReporteVenta.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ReporteVenta.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ReporteVenta.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ReporteVenta.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ReporteVenta().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btImprimir;
    private javax.swing.JDialog dialogo;
    private javax.swing.JButton jBSalir;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JLabel label3;
    private javax.swing.JLabel lbCedulaRif;
    private javax.swing.JLabel lbDireccion;
    private javax.swing.JLabel lbNombre;
    private javax.swing.JLabel lbNumeroVenta;
    private javax.swing.JLabel lbfecha;
    private javax.swing.JList listaFacturas;
    private javax.swing.JTable tablaFactura;
    private javax.swing.JTextArea texto;
    private javax.swing.JTextField tfBusqueda;
    private javax.swing.JTextField tfIva;
    private javax.swing.JTextField tfSubTotal;
    private javax.swing.JTextField tfTotal;
    // End of variables declaration//GEN-END:variables
}
