/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package sistema.de.facturacion;

import java.awt.Component;
import java.awt.Container;
import java.awt.event.WindowAdapter;
import java.awt.event.WindowEvent;
import java.awt.event.WindowListener;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.DefaultListModel;
import javax.swing.JOptionPane;
import sistema.de.facturacion.menu;

/**
 *
 * @author Julio
 */
public class Usuario extends javax.swing.JFrame {

    private DefaultListModel modeloListaUsuario;
    private ResultSet rsUsuarioBuscados;

    public Usuario() {
        initComponents();
        enableComponents(panelDatos, true);
        modeloListaUsuario = (DefaultListModel) listaUsuario.getModel();
        this.setLocationRelativeTo(null);
        WindowListener exitListener = new WindowAdapter() {

            @Override
            public void windowClosing(WindowEvent e) {
                new Login().setVisible(true);
            }
        };
        this.addWindowListener(exitListener);
        
         btBuscarMouseClicked(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane2 = new javax.swing.JScrollPane();
        listaUsuario = new javax.swing.JList();
        panelDatos = new javax.swing.JPanel();
        btAgregar = new javax.swing.JButton();
        btLimpiar = new javax.swing.JButton();
        tfClave = new javax.swing.JTextField();
        tfNombre = new javax.swing.JTextField();
        tfCedula = new javax.swing.JTextField();
        tfLogin = new javax.swing.JTextField();
        jLabel17 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        tfClienteBuscar = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jButton7 = new javax.swing.JButton();
        btBuscar = new javax.swing.JButton();
        btModificar = new javax.swing.JButton();
        btEliminar = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        listaUsuario.setModel(new DefaultListModel());
        listaUsuario.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                listaUsuarioMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(listaUsuario);

        getContentPane().add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 170, 240, 180));

        panelDatos.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));
        panelDatos.setOpaque(false);
        panelDatos.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btAgregar.setText("Agregar");
        btAgregar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btAgregarMouseClicked(evt);
            }
        });
        btAgregar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btAgregarActionPerformed(evt);
            }
        });
        panelDatos.add(btAgregar, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 170, 120, 50));

        btLimpiar.setText("Limpiar");
        btLimpiar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btLimpiarMouseClicked(evt);
            }
        });
        panelDatos.add(btLimpiar, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 170, 110, 50));
        panelDatos.add(tfClave, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 130, 200, 30));

        tfNombre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfNombreActionPerformed(evt);
            }
        });
        panelDatos.add(tfNombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 90, 200, 30));

        tfCedula.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfCedulaActionPerformed(evt);
            }
        });
        panelDatos.add(tfCedula, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 50, 200, 30));

        tfLogin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfLoginActionPerformed(evt);
            }
        });
        panelDatos.add(tfLogin, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 10, 200, 30));

        jLabel17.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel17.setForeground(new java.awt.Color(255, 255, 255));
        jLabel17.setText("Login");
        panelDatos.add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 60, -1));

        jLabel11.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(255, 255, 255));
        jLabel11.setText("Cedula");
        panelDatos.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 50, -1, -1));

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Nombre");
        panelDatos.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 90, 60, 40));

        jLabel7.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("clave");
        panelDatos.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 130, 60, 40));

        getContentPane().add(panelDatos, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 80, 350, 240));

        jLabel16.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/SIGCA(LOGO)_1 pequeño.png"))); // NOI18N
        getContentPane().add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 420, 220, 80));

        tfClienteBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfClienteBuscarActionPerformed(evt);
            }
        });
        tfClienteBuscar.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                tfClienteBuscarKeyReleased(evt);
            }
        });
        getContentPane().add(tfClienteBuscar, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 60, 170, 30));

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Datos del Usuario");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 40, 170, 40));

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Usuarios");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 20, 70, 30));

        jButton7.setText("Atras");
        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton7, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 450, 120, 50));

        btBuscar.setText("Buscar");
        btBuscar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btBuscarMouseClicked(evt);
            }
        });
        getContentPane().add(btBuscar, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 100, 170, 40));

        btModificar.setText("Modificar");
        btModificar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btModificarMouseClicked(evt);
            }
        });
        btModificar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btModificarActionPerformed(evt);
            }
        });
        getContentPane().add(btModificar, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 360, 100, 50));

        btEliminar.setText("Eliminar");
        btEliminar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btEliminarMouseClicked(evt);
            }
        });
        getContentPane().add(btEliminar, new org.netbeans.lib.awtextra.AbsoluteConstraints(730, 360, 100, 50));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/WINDOWS_7_WALLPAPER_BY_AMYSTIKALDESIGNS.JPG"))); // NOI18N
        jLabel1.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                jLabel1MouseMoved(evt);
            }
        });
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 930, 510));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jLabel1MouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel1MouseMoved

        // TODO add your handling code here:
    }//GEN-LAST:event_jLabel1MouseMoved

    private void tfCedulaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfCedulaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfCedulaActionPerformed

    private void tfNombreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfNombreActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfNombreActionPerformed

    private void tfClienteBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfClienteBuscarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfClienteBuscarActionPerformed

    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7ActionPerformed

        Login principal = new Login();
        dispose();

        principal.setLocationRelativeTo(null);
        principal.setVisible(true);

        // TODO add your handling code here:
    }//GEN-LAST:event_jButton7ActionPerformed

    public void enableComponents(Container container, boolean enable) {
        Component[] components = container.getComponents();
        for (Component component : components) {
            component.setEnabled(enable);
            if (component instanceof Container) {
                enableComponents((Container) component, enable);
            }
        }
    }

    private void btAgregarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btAgregarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btAgregarActionPerformed

    private void btLimpiarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btLimpiarMouseClicked
       tfCedula.setText("");
        tfNombre.setText("");
        tfClave.setText("");
        tfLogin.setText("");
    }//GEN-LAST:event_btLimpiarMouseClicked

    private void btAgregarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btAgregarMouseClicked
        if (tfNombre.equals("") || tfCedula.equals("")) {
            JOptionPane.showMessageDialog(null, "Debe escribir que tipo de usuario es y una Clave");
            return;
        } else {
            try {
                if (btAgregar.getText().equals("Agregar")) {

                    PreparedStatement pps = Conexion.getConnection().prepareStatement(""
                            + "INSERT INTO usuario("
                            + " nombre_usuario, claveacceso, descripcion_usuario, cedula_usuario)"
                            + " VALUES (?, ?, ?, ?);");

                    pps.setString(1, tfLogin.getText());
                    pps.setString(2, tfClave.getText());
                    pps.setString(3, tfNombre.getText());
                    pps.setString(4, tfCedula.getText());
                    pps.executeUpdate();

                    JOptionPane.showMessageDialog(null, "Se ha creado un nuevo usuario");

                } else {//MODIFICAR

                    PreparedStatement pps = Conexion.getConnection().prepareStatement("UPDATE usuario"
                            + "   SET nombre_usuario=?, claveacceso=?, descripcion_usuario=?, cedula_usuario=?"
                            + " WHERE id_usuario = ?");

                     pps.setString(1, tfLogin.getText());
                    pps.setString(2, tfClave.getText());
                    pps.setString(3, tfNombre.getText());
                    pps.setString(4, tfCedula.getText());
                    pps.setObject(5, rsUsuarioBuscados.getInt("id_usuario"));
                    pps.executeUpdate();

                    JOptionPane.showMessageDialog(null, "Se ha modificado el registro");
                    btBuscarMouseClicked(null);
                    btAgregar.setText("Agregar");
                }

                btLimpiarMouseClicked(null);
                enableComponents(panelDatos, false);
            } catch (Exception ex) {
                JOptionPane.showMessageDialog(null, "Ha ocurido un error en la insercion de los datos");
                Logger.getLogger(Usuario.class.getName()).log(Level.SEVERE, null, ex);
            }

        }
    }//GEN-LAST:event_btAgregarMouseClicked

    private void btBuscarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btBuscarMouseClicked
        //rsClientesBuscados
       

            String sql = "SELECT nombre_usuario, claveacceso, descripcion_usuario, cedula_usuario, id_usuario"
                    + "  FROM usuario WHERE usuario.nombre_usuario like '%" + tfClienteBuscar.getText() + "%'";

            try {
                Statement st = Conexion.getConnection().createStatement(ResultSet.TYPE_SCROLL_SENSITIVE, ResultSet.CONCUR_READ_ONLY);
                rsUsuarioBuscados = st.executeQuery(sql);
                modeloListaUsuario = new DefaultListModel();
                while (rsUsuarioBuscados.next()) {
                    modeloListaUsuario.addElement(rsUsuarioBuscados.getObject("nombre_usuario"));
                }
                listaUsuario.setModel(modeloListaUsuario);
            } catch (SQLException ex) {
                Logger.getLogger(Login.class.getName()).log(Level.SEVERE, null, ex);
            }


    }//GEN-LAST:event_btBuscarMouseClicked

    private void btModificarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btModificarMouseClicked

        try {
            if (rsUsuarioBuscados == null || listaUsuario.getSelectedIndex() == -1) {
                return;
            }

            enableComponents(panelDatos, true);
            btLimpiarMouseClicked(null);
            btAgregar.setText("Modificar");
            tfLogin.setText(rsUsuarioBuscados.getString("nombre_usuario"));
            tfCedula.setText(rsUsuarioBuscados.getString("cedula_usuario"));
            tfNombre.setText(rsUsuarioBuscados.getString("descripcion_usuario"));
            tfClave.setText(rsUsuarioBuscados.getString("claveacceso"));

        } catch (SQLException ex) {
            Logger.getLogger(Usuario.class.getName()).log(Level.SEVERE, null, ex);
        }

    }//GEN-LAST:event_btModificarMouseClicked

    private void btEliminarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btEliminarMouseClicked
        //rsClientesBuscados
        if (rsUsuarioBuscados == null || listaUsuario.getSelectedIndex() == -1) {
            return;
        }

        try {
            PreparedStatement pps = Conexion.getConnection().prepareStatement(""
                    + "DELETE FROM usuario WHERE id_usuario = ?");

            pps.setObject(1, rsUsuarioBuscados.getInt("id_usuario"));
            pps.executeUpdate();

            JOptionPane.showMessageDialog(null, "Se ha eliminado el registro");
            btBuscarMouseClicked(null);
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(null, "Ha ocurido un error en la eliminacion de los datos");
            Logger.getLogger(Usuario.class.getName()).log(Level.SEVERE, null, ex);
        }

    }//GEN-LAST:event_btEliminarMouseClicked

    private void listaUsuarioMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_listaUsuarioMouseClicked
        try {
            rsUsuarioBuscados.beforeFirst();
            for (int i = 0; i <= listaUsuario.getSelectedIndex(); i++) {
                rsUsuarioBuscados.next();
            }
        } catch (SQLException ex) {
            Logger.getLogger(Usuario.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_listaUsuarioMouseClicked

    private void btModificarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btModificarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btModificarActionPerformed

    private void tfClienteBuscarKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tfClienteBuscarKeyReleased
        btBuscarMouseClicked(null);
    }//GEN-LAST:event_tfClienteBuscarKeyReleased

    private void tfLoginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfLoginActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfLoginActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Usuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Usuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Usuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Usuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Usuario().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btAgregar;
    private javax.swing.JButton btBuscar;
    private javax.swing.JButton btEliminar;
    private javax.swing.JButton btLimpiar;
    private javax.swing.JButton btModificar;
    private javax.swing.JButton jButton7;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JList listaUsuario;
    private javax.swing.JPanel panelDatos;
    private javax.swing.JTextField tfCedula;
    private javax.swing.JTextField tfClave;
    private javax.swing.JTextField tfClienteBuscar;
    private javax.swing.JTextField tfLogin;
    private javax.swing.JTextField tfNombre;
    // End of variables declaration//GEN-END:variables
}
