/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package sistema.de.facturacion;

import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.DefaultListModel;
import javax.swing.JOptionPane;
import javax.swing.SpinnerNumberModel;
import javax.swing.table.DefaultTableModel;
import sistema.de.facturacion.menu;

/**
 *
 * @author Luis
 */
public class Venta extends javax.swing.JFrame {

    /**
     * Creates new form proovedor
     */
    private ResultSet rsProductoBuscado;
    private ResultSet rsClienteBuscado;
    private DefaultTableModel modeloTabla;

    public Venta() {
        initComponents();
        modeloTabla = (DefaultTableModel) jTabledeventa.getModel();
        configure();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel8 = new javax.swing.JLabel();
        tfTotal = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        tfSubTotal = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        tfIva = new javax.swing.JTextField();
        jTCliente = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        btBuscarProducto = new javax.swing.JButton();
        tfProducto = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jTcedulaorif = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jBVer = new javax.swing.JButton();
        jBNueva = new javax.swing.JButton();
        jBSalir = new javax.swing.JButton();
        jBImprimir = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTabledeventa = new javax.swing.JTable();
        btAgregarProducto = new javax.swing.JButton();
        crearVenta = new javax.swing.JButton();
        jBuscar = new javax.swing.JButton();
        jBModificar = new javax.swing.JButton();
        btEliminarRenglon = new javax.swing.JButton();
        lbCantidadTotalProducto = new javax.swing.JLabel();
        spCantidad = new javax.swing.JSpinner();
        lbNumeroVenta = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel8.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("SUBTOTAL");
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 450, -1, -1));

        tfTotal.setEditable(false);
        getContentPane().add(tfTotal, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 450, 110, -1));

        jLabel10.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setText("TOTAL A PAGAR");
        getContentPane().add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 450, -1, -1));

        tfSubTotal.setEditable(false);
        getContentPane().add(tfSubTotal, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 450, 90, -1));

        jLabel9.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("IVA");
        getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 440, 40, 30));

        tfIva.setEditable(false);
        tfIva.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfIvaActionPerformed(evt);
            }
        });
        getContentPane().add(tfIva, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 450, 120, -1));

        jTCliente.setEditable(false);
        getContentPane().add(jTCliente, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 130, 170, -1));

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel6.setText("Cliente");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 130, 40, 20));

        jLabel7.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel7.setText("Cantidad");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 170, -1, -1));

        btBuscarProducto.setText("Buscar");
        btBuscarProducto.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btBuscarProductoMouseClicked(evt);
            }
        });
        getContentPane().add(btBuscarProducto, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 160, 100, 30));
        getContentPane().add(tfProducto, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 170, 140, 30));

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel5.setText("PRODUCTO");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 180, -1, -1));
        getContentPane().add(jTcedulaorif, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 130, 140, 30));

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel2.setText("CEDULA O RIF");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 130, -1, -1));

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel4.setText("NUMERO DE VENTA");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 70, -1, -1));

        jBVer.setText("Ver");
        getContentPane().add(jBVer, new org.netbeans.lib.awtextra.AbsoluteConstraints(750, 170, 90, 40));

        jBNueva.setText("Nueva");
        getContentPane().add(jBNueva, new org.netbeans.lib.awtextra.AbsoluteConstraints(750, 120, 90, 40));

        jBSalir.setText("Salir");
        getContentPane().add(jBSalir, new org.netbeans.lib.awtextra.AbsoluteConstraints(750, 220, 90, 40));

        jBImprimir.setText("Imprimir");
        getContentPane().add(jBImprimir, new org.netbeans.lib.awtextra.AbsoluteConstraints(750, 70, 90, 40));

        jTabledeventa.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Codigo", "Producto", "Descripcion", "Cantidad", "Precio", "Importe"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTabledeventa.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        jTabledeventa.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTabledeventaMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(jTabledeventa);

        getContentPane().add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 240, 410, 180));

        btAgregarProducto.setText("Agregar");
        btAgregarProducto.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btAgregarProductoMouseClicked(evt);
            }
        });
        getContentPane().add(btAgregarProducto, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 160, 90, 30));

        crearVenta.setText("Facturar");
        crearVenta.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                crearVentaMouseClicked(evt);
            }
        });
        crearVenta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                crearVentaActionPerformed(evt);
            }
        });
        getContentPane().add(crearVenta, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 340, 160, 50));

        jBuscar.setText("Buscar");
        jBuscar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jBuscarMouseClicked(evt);
            }
        });
        getContentPane().add(jBuscar, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 120, 100, 30));

        jBModificar.setText("Modificar");
        getContentPane().add(jBModificar, new org.netbeans.lib.awtextra.AbsoluteConstraints(750, 270, 90, 40));

        btEliminarRenglon.setText("Eliminar");
        btEliminarRenglon.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btEliminarRenglonMouseClicked(evt);
            }
        });
        getContentPane().add(btEliminarRenglon, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 290, 90, 30));
        getContentPane().add(lbCantidadTotalProducto, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 170, 60, 20));

        spCantidad.setModel(new javax.swing.SpinnerNumberModel(Integer.valueOf(1), Integer.valueOf(1), null, Integer.valueOf(1)));
        getContentPane().add(spCantidad, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 170, 60, -1));

        lbNumeroVenta.setFont(new java.awt.Font("Tahoma", 2, 14)); // NOI18N
        getContentPane().add(lbNumeroVenta, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 70, 170, 20));

        jLabel16.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/SIGCA(LOGO)_1 pequeño.png"))); // NOI18N
        getContentPane().add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 410, 220, 80));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/WINDOWS_7_WALLPAPER_BY_AMYSTIKALDESIGNS.JPG"))); // NOI18N
        jLabel1.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                jLabel1MouseMoved(evt);
            }
        });
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 930, 510));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void crearVentaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_crearVentaActionPerformed

    }//GEN-LAST:event_crearVentaActionPerformed

    private void jLabel1MouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel1MouseMoved

        // TODO add your handling code here:
    }//GEN-LAST:event_jLabel1MouseMoved

    private void configure() {
        btAgregarProducto.setEnabled(false);
        btEliminarRenglon.setEnabled(false);
        crearVenta.setEnabled(false);
        jTcedulaorif.setText("");
        tfProducto.setText("");
        jTCliente.setText("");
        tfSubTotal.setText("");
        tfIva.setText("");
        tfTotal.setText("");
        for (int i = 0; i < modeloTabla.getRowCount(); i++) {
            modeloTabla.removeRow(0);
        }

        /*        String sql = "select CURRVAL('venta_id_venta_seq') as valor";

         try {
         Statement st = Conexion.getConnection().createStatement(ResultSet.TYPE_SCROLL_SENSITIVE, ResultSet.CONCUR_READ_ONLY);
         ResultSet currVal = st.executeQuery(sql);
         if (currVal.next()) {
         lbNumeroVenta.setText(currVal.getInt("valor")+"");
         } else {
         lbNumeroVenta.setText("");
         }
         } catch (SQLException ex) {
         Logger.getLogger(Login.class.getName()).log(Level.SEVERE, null, ex);
         }
         */
    }

    private void tfIvaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfIvaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfIvaActionPerformed

    private void jBuscarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jBuscarMouseClicked
        if (jTcedulaorif.getText().equals("")) {
            JOptionPane.showMessageDialog(null, "Debe escribir que tipo de usuario es y una Clave");
            return;
        } else {

            String sql = "SELECT rif, nombre_cliente, apellido_cliente, domicilio_cliente, id_tcliente, "
                    + "       email_cliente, tlf_cliente, serial, cedula_cliente "
                    + "  FROM cliente WHERE cliente.cedula_cliente = '" + jTcedulaorif.getText() + "' OR "
                    + "cliente.rif = '" + jTcedulaorif.getText() + "'";

            try {
                Statement st = Conexion.getConnection().createStatement(ResultSet.TYPE_SCROLL_SENSITIVE, ResultSet.CONCUR_READ_ONLY);
                rsClienteBuscado = st.executeQuery(sql);
                if (rsClienteBuscado.next()) {
                    jTCliente.setText(rsClienteBuscado.getString("nombre_cliente") + " " + rsClienteBuscado.getString("apellido_cliente"));
                } else {
                    rsClienteBuscado = null;
                    jTCliente.setText("");
                }
            } catch (SQLException ex) {
                Logger.getLogger(Login.class.getName()).log(Level.SEVERE, null, ex);
            }

        }
    }//GEN-LAST:event_jBuscarMouseClicked

    private void btBuscarProductoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btBuscarProductoMouseClicked
        String sql = "SELECT nombre_producto, descripcion_producto, id_tproducto, precio_producto, "
                + " id_producto, cantidad"
                + " FROM producto WHERE producto.nombre_producto ='" + tfProducto.getText() + "' AND producto.cantidad > 0";

        try {
            Statement st = Conexion.getConnection().createStatement(ResultSet.TYPE_SCROLL_SENSITIVE, ResultSet.CONCUR_READ_ONLY);
            rsProductoBuscado = st.executeQuery(sql);
            if (rsProductoBuscado.next()) {
                lbCantidadTotalProducto.setText(rsProductoBuscado.getInt("cantidad") + "");
                btAgregarProducto.setEnabled(true);
                spCantidad.setModel(new SpinnerNumberModel(1, 1, rsProductoBuscado.getInt("cantidad"), 1));
            } else {
                rsProductoBuscado = null;
                lbCantidadTotalProducto.setText("");
                btAgregarProducto.setEnabled(false);
            }
        } catch (SQLException ex) {
            Logger.getLogger(Login.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btBuscarProductoMouseClicked

    private void btAgregarProductoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btAgregarProductoMouseClicked
        try {
            modeloTabla.addRow(new Object[]{
                rsProductoBuscado.getInt("id_producto"),
                rsProductoBuscado.getString("nombre_producto"),
                rsProductoBuscado.getString("descripcion_producto"),
                (int) spCantidad.getValue(),
                rsProductoBuscado.getFloat("precio_producto"),
                rsProductoBuscado.getFloat("precio_producto") * (int) spCantidad.getValue()
            });
            updateTotals();
        } catch (SQLException ex) {
            Logger.getLogger(Venta.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btAgregarProductoMouseClicked

    private void jTabledeventaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTabledeventaMouseClicked
        btEliminarRenglon.setEnabled(jTabledeventa.getSelectedRow() != -1);
    }//GEN-LAST:event_jTabledeventaMouseClicked

    private void btEliminarRenglonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btEliminarRenglonMouseClicked
        if (jTabledeventa.getSelectedRow() != -1) {
            modeloTabla.removeRow(jTabledeventa.getSelectedRow());
            updateTotals();
        }
    }//GEN-LAST:event_btEliminarRenglonMouseClicked

    private void crearVentaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_crearVentaMouseClicked
        try {
            PreparedStatement pps = Conexion.getConnection().prepareStatement(""
                    + "INSERT INTO venta("
                    + " total_venta,id_usuario,id_cliente)"
                    + " VALUES (?,?,?);", Statement.RETURN_GENERATED_KEYS);

            pps.setFloat(1, Float.parseFloat(tfTotal.getText()));
            pps.setInt(2, Login.usr.getID());
            pps.setInt(3, rsClienteBuscado.getInt("serial"));
            pps.executeUpdate();
            ResultSet generatedKeys = pps.getGeneratedKeys();
            generatedKeys.next();
            lbNumeroVenta.setText(generatedKeys.getLong(1) + "");

            for (int i = 0; i < modeloTabla.getRowCount(); i++) {
                PreparedStatement pps2 = Conexion.getConnection().prepareStatement(""
                        + "INSERT INTO detalle_venta("
                        + " cantidad, importe, id_producto, id_venta)"
                        + " VALUES (?,?,?,?);");

                pps2.setInt(1, (int) modeloTabla.getValueAt(i, 3));
                pps2.setFloat(2, (Float) modeloTabla.getValueAt(i, 5));
                pps2.setInt(3, (int) modeloTabla.getValueAt(i, 0));
                pps2.setLong(4, generatedKeys.getLong(1));
                pps2.executeUpdate();
                configure();
            }
        } catch (SQLException ex) {
            Logger.getLogger(Venta.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_crearVentaMouseClicked

    private void updateTotals() {
        float subTOtal = 0;
        for (int i = 0; i < modeloTabla.getRowCount(); i++) {
            subTOtal += (Float) modeloTabla.getValueAt(i, 5);
        }
        crearVenta.setEnabled(subTOtal != 0);
        tfSubTotal.setText(subTOtal + "");
        tfIva.setText((subTOtal * 0.12) + "");
        tfTotal.setText((subTOtal * 1.12) + "");
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Venta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Venta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Venta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Venta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Venta().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btAgregarProducto;
    private javax.swing.JButton btBuscarProducto;
    private javax.swing.JButton btEliminarRenglon;
    private javax.swing.JButton crearVenta;
    private javax.swing.JButton jBImprimir;
    private javax.swing.JButton jBModificar;
    private javax.swing.JButton jBNueva;
    private javax.swing.JButton jBSalir;
    private javax.swing.JButton jBVer;
    private javax.swing.JButton jBuscar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextField jTCliente;
    private javax.swing.JTable jTabledeventa;
    private javax.swing.JTextField jTcedulaorif;
    private javax.swing.JLabel lbCantidadTotalProducto;
    private javax.swing.JLabel lbNumeroVenta;
    private javax.swing.JSpinner spCantidad;
    private javax.swing.JTextField tfIva;
    private javax.swing.JTextField tfProducto;
    private javax.swing.JTextField tfSubTotal;
    private javax.swing.JTextField tfTotal;
    // End of variables declaration//GEN-END:variables
}
